# Generated by Django 4.2.10 on 2024-02-21 20:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_article_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.CharField(max_length=250, null=True)),
                ('image', models.ImageField(blank=True, upload_to='news_images')),
            ],
        ),
    ]
