# Generated by Django 4.2.10 on 2024-02-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
