# Generated by Django 4.2.10 on 2024-02-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0012_news_created_at_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(default='https://www.google.com'),
            preserve_default=False,
        ),
    ]
