# Generated by Django 4.2.7 on 2024-02-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0016_article_thumbnail_user_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mini_thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails'),
        ),
    ]
